name: Mentor Web Store
favicon: null
layout_spectrum: 0.7587844806257635
typography_spectrum: 0.15866321395151317
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4219830797519535
  lightness: 0.9178886490408331
  saturation: 0.4876771888229996
  rhythmicContrast: 0.4662593347020447
purpose: []
